version: 2
jobs:
  build:
    working_directory: ~/contact-tasks
    docker:
      - image: circleci/openjdk:8u212-jdk-stretch
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline
      - run: mvn test
      - run: "bash <(curl -s https://codecov.io/bash)"

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - store-artifacts:
          path: target